
FROM node:24-alpine AS builder
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH


COPY package*.json ./
RUN npm ci --silent

# copy sources and build
COPY . .
RUN npm run build

# runtime image
FROM node:24-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
ENV PORT=3000

# only production deps
COPY package*.json ./
RUN npm ci --only=production --silent

# copy built app
COPY --from=builder /app/dist ./dist

EXPOSE 3000
USER node

# start the app (expects a "start:prod" script or adjust to `node dist/main.js`)
CMD ["npm", "run", "start:prod"]